replicaCount: 1
image:
  pullPolicy: IfNotPresent
  repository: dohhighacrcodefresh.azurecr.io/flask-ui
  tag: main-15775a4
  pullSecret: 
    - name: 'dohhighacrcodefresh'
service:
  name: flask-ui
  type: ClusterIP
  externalPort: 80
  internalPort: 5000
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
ingress:
  enabled: false
