replicaCount: 1
image:
  pullPolicy: IfNotPresent
  repository: dohhighacrcodefresh.azurecr.io/buslog
  tag: main-f505305
  pullSecret: 'dohhighacrcodefresh'
service:
  name: buslog
  type: ClusterIP
  externalPort: 80
  internalPort: 5000
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
ingress:
  enabled: false
